language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

branches:
  only:
    - develop
    - master

env:
  - LAUNCHER=console
  - LAUNCHER=phar

before_script:
  # Mailcacher server
  - gem install mailcatcher
  - mailcatcher
  - echo 'sendmail_path = "/usr/bin/env /var/lib/gems/1.8/bin/catchmail "' | sudo tee "/home/travis/.phpenv/versions/`php -i|grep "PHP Version"|head -n 1|grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"

  # Database
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'DROP DATABASE IF EXISTS `wp_v381`; CREATE DATABASE `wp_v381` /*!40100 CHARACTER SET utf8 COLLATE 'utf8_general_ci' */;'

  # Dependencies
  - composer self-update && composer --version
  - composer install --prefer-source --no-interaction --dev
  - wget http://codeception.com/codecept.phar

script:
  - php codecept.phar run functional --steps --env $LAUNCHER

notifications:
  email:
    on_success: never
    on_failure: change